name: Tests
on: push
jobs:
  workflows:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest]
        node_version: ["14", "16", "18"]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}
      - name: Install modules
        run: yarn
      - name: Build contract
        run: yarn build
      - name: Run tests
        run: yarn test
