name: Tests
on:
  pull_request:
  push:
    branches:
      - master
      - develop

jobs:
  workflows_ubuntu:
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Install modules
        run: yarn
      - name: Build contract
        run: yarn build
      - name: Set master credentials
        env:
          TESTNET_MASTER_ACCOUNT_WALLET: ${{ secrets.TESTNET_MASTER_ACCOUNT_WALLET }}
        run: echo "$TESTNET_MASTER_ACCOUNT_WALLET" > .near-credentials/workspaces/testnet/templateprojectmaster.testnet.json
      - name: Run ci tests
        run: yarn testci
      - name: Run near-cli tests
        run: yarn run test:clidevdeploy

  workflows_macos:
    needs: workflows_ubuntu
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Install modules
        run: yarn
      - name: Build contract
        run: yarn build
      - name: Set master credentials
        env:
          TESTNET_MASTER_ACCOUNT_WALLET: ${{ secrets.TESTNET_MASTER_ACCOUNT_WALLET }}
        run: echo "$TESTNET_MASTER_ACCOUNT_WALLET" > .near-credentials/workspaces/testnet/templateprojectmaster.testnet.json
      - name: Run ci tests
        run: yarn testci
      - name: Run near-cli tests
        run: yarn run test:clidevdeploy
